version: "3.9"
services:
  app:
    build:
      args:
        user: gestor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gestor
    container_name: gestor-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./php/gestor:/var/www
      - ./docker/php-fpm.conf:/etc/php/php-fpm.d/www.conf
      - ./docker/php.ini:/etc/php/conf.d/php.ini
    networks:
      - gestor

  postgresql:
    image: postgres:latest
    container_name: gestor-postgresql
    restart: unless-stopped
    environment:
      PGPASSWORD: postgres
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: gestor
      POSTGRES_DB: gestor
    volumes:
      - ~/.config/postgresql/data:/var/lib/postgresql/data
    networks:
      - gestor

  nginx:
    image: nginx:latest
    container_name: nginx-gestor
    ports:
      - "80:80"
    volumes:
      - ./php/gestor:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gestor
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@localhost.dev
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    networks:
      - gestor

networks:
  gestor:
    driver: bridge